# Form implementation generated from reading ui file 'DiceWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(813, 493)
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.connectButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.connectButton.setGeometry(QtCore.QRect(20, 20, 211, 41))
        self.connectButton.setObjectName("connectButton")
        self.readyButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.readyButton.setGeometry(QtCore.QRect(480, 20, 151, 41))
        self.readyButton.setObjectName("readyButton")
        self.playernameLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.playernameLine.setGeometry(QtCore.QRect(290, 20, 181, 31))
        self.playernameLine.setText("")
        self.playernameLine.setObjectName("playernameLine")
        self.diceBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.diceBox.setGeometry(QtCore.QRect(20, 100, 611, 251))
        self.diceBox.setTitle("")
        self.diceBox.setObjectName("diceBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.diceBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 581, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.batteryLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.batteryLabel.setText("")
        self.batteryLabel.setObjectName("batteryLabel")
        self.verticalLayout.addWidget(self.batteryLabel)
        self.rollLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.rollLabel.setText("")
        self.rollLabel.setObjectName("rollLabel")
        self.verticalLayout.addWidget(self.rollLabel)
        self.stabilityLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.stabilityLabel.setText("")
        self.stabilityLabel.setObjectName("stabilityLabel")
        self.verticalLayout.addWidget(self.stabilityLabel)
        self.responseLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.responseLabel.setText("")
        self.responseLabel.setObjectName("responseLabel")
        self.verticalLayout.addWidget(self.responseLabel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 813, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DiceRoller Python"))
        self.connectButton.setText(_translate("MainWindow", "Connect Dice"))
        self.readyButton.setText(_translate("MainWindow", "Ready"))
        self.playernameLine.setPlaceholderText(_translate("MainWindow", "Enter player name."))
